config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => "homes#about", as: "about"


  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user


  def get image
      unless image.attached?
          file_path = Rails.root.join('bookers2/default-image.jpg')
          image.attach(io: file.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')

      end
      image
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end



  has_one_attached :profile_image
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top,:about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created a book successfully"
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated the book successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "You have destroyed the book successfully."
    redirect_to books_path
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

private

  def book_params
    params.require(:book).permit(:title, :body)

  end

  def ensure_correct_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @user = User.find(params[:id])
    @users = User.all
    @book = Book.new

  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user information successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="row">
  <div class="col-md-3">
    <sidebar>
      <h1>User info</h1>
      <%= image_tag user.get_profile_image(100,100) %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.current_user.id %></th>
          </tr>
          <tr>
            <th>Introduction</th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block"></a>
      </div>

    </sidebar>

<sidebar>
<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>

<div class="form-group">
<label for="book_title">Title</label>
<input class="form-control book_title" type="text" name="book[title]" id="book_title">

<div class="form-group">
  <label for="book_opinion">Opinion</label>
  <textarea class="form-control book_body" name="book[body]" id="book_body"></textarea>
</div>

<div class="form-group">
  <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book">
</div>
</div>

<% end %>

</sidebar>

</div>

app/views/books/edit.html.erb
<!--#本の編集ページ-->
<body>
  <main>
    <div class="conteiner">

      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
    <%= render 'layouts/error', obj: @book %>

    <%= form_with model: @book do |f| %>

      <div class="form-group">
      <label for="inputTitle">Title</label>
      <%= f.text_field :title, autofocus: true, id:"inputName", placefolder:"タイトル" %>
      </div>

      <div class="form-group">
        <label for="inputBody">Opinion</label>
        <%= f.text_field :body, autofocus: true, id:"inpubody", placefolder:"タイトル" %>
      </div>

      <div class="form-group">
        <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
      </div>
      <% end %>

      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>

        </div>
      </div>
    </div>
  </main>
</body>

app/views/books/index.html.erb
<!--#Books一覧-->
<div class="container px-5 px-sm-0">
   <%= render 'layouts/error', obj: @book %>

  <div class="row">
    <div class="col-md-3">
<%= render 'book', book: @book, user: @user %>
    </div>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
    <tr>
     <span>
    <td>
    <%= link_to user_path(book.user_id) do %>
    <%= image_tag book.user.get_profile_image(80,80) %>
    <% end %>
    </td>
    <td>
      <%= link_to book_path(book.id) do %>
      <%= book.title %>
      <% end %>
    </td>
    <td><%= book.body %></td>
    </span>
    </tr>

    <% end %>

  </tbody>
  </table>
  </div>
  </div>
</div>

app/views/books/show.html.erb
<!--#本の詳細ページ-->
<div class="conteiner">
  <div class="row">
    <div class="col-md-3">
<%= render 'book', books: @books, user: @user %>
    </div>

<div class="col-md-8 offset-md-1">
  <h2>Book datail</h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
    <%= link_to user_path(@user) do %>
     <span>
      <td>
      <%= image_tag post_image.user.get_profile_image(80,80) %>
      </td>
    <td>
      <%= @user.name %>
      <% end %>
    </td>
      <%= link_to book_path(@book) %>
    <td><%= book.title %></td>
      <% end %>
    <td>
      <%= book.body %>
    </td>
    <% if @user == current.user %>
    <td>
      <%= link_to "Edit", edit_book_path(@book) %>
    </td>

    <td>
       <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
    </td>
    </span>
    </tr>

    <% end %>

  </tbody>
</table>
</div>
</div>
</div>

app/views/homes/about.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>!!
        </h1>
        <p>In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_error.html.erb
<div>
  <% if obj.errors.any? %>
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user) do %>
         <i class="fas fa-home" aria-hidden="true"></i> Home</i>
        <% end %>
      </li>
      <li>
        <%= link_to users_path do %>
        <i class="fas fa-users" aria-hidden="true"></i> Users</i>
        <% end %>
      </li>
      <li>
        <%= link_to books_path do %>
        <i class="fas fa-book-open" aria-hidden="true"></i> Books</i>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt" aria-hidden="true"></i> Log out</i>
        <% end %>
      </li>
    <% else %>


          <li>
            <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6cf21f571b.js" crossorigin="anonymous">

  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <p class="notice"><%= notice %></p>
    <%= yield %>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<!--#User編集ページ-->
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">


    <h2>User info</h2>
    <%= render 'layouts/error', obj: @user %>

    <%= form_with model: @user do |f| %>
    <div>
      <label for="inputName">Name</label>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
    </div>
    <div>
      <label for="inputImage">Image</label>
      <%= f.field :profile_image, placeholder:"プロフィール画像", accept: "image/*" %>
    </div>
    <div>
      <label for="inputBody">Introduction</label>
      <%= f.text_area :introduction, autofocus: true, id:"inputBody" %>
    </div>
    <div>
      <%= f.submit "Update User" %>
    </div>
    <% end %>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<!--ユーザー一覧-->
<div class="conteiner px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<%= render 'book', book: @book, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>

<table>
  <thead>
    <tr>
    <th>Image</th>
    <th>name</th>
    <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
   <tr>
     <span>
     <%= @users.each do |user| %>
      <td><%= image_tag user.get_profile_image(80,80) %></td>
      <td><%= user.name %></td>
      <td>
      <%= link_to "Show", user_path(user.id) %>
      </td>
      </span>
    </tr>

  <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<!--User詳細ページ-->
<div class="conteiner px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
<%= render 'book', book: @book, user: @user %>
    </div>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table>
    <thead>
      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user_id) %>
          <%= image_tag book.user.get_profile_image(80,80) %>
        <% end %>
      </td>
      <td>
        <%= link_to book_path(book.id) %>
          <%= book.title %>
        <% end %>
      </td>
      <td>
        <%= book.body %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
  </div>
  </div>
</div>